title: Superagile
description: Superagile framework, approach, and culture. Created by Concise.
theme: just-the-docs

url: ""

aux_links:
  Concise: https://concise.ee/
  # Template Repository: https://github.com/just-the-docs/just-the-docs-template
