title: "#superagile"
description: Superagile framework, approach, and culture. Created by Concise.
theme: just-the-docs
color_scheme: dark

url: ""

aux_links:
  concise: https://concise.ee/
  # Template Repository: https://github.com/just-the-docs/just-the-docs-template


callouts:
  warning-signs:
    title: What not having it looks like
    color: yellow
